// Example data
window.PRODUCTS = [
  {
    id: 1,
    title: "Wireless Headphones X1",
    category: "Audio",
    price: 2999,
    rating: 4.6,
  },
  {
    id: 2,
    title: "Mechanical Keyboard K84",
    category: "Accessories",
    price: 4499,
    rating: 4.7,
  },
  {
    id: 3,
    title: "1080p Web Camera",
    category: "Accessories",
    price: 1899,
    rating: 4.2,
  },
  {
    id: 4,
    title: "Smartwatch FitGo",
    category: "Wearables",
    price: 5299,
    rating: 4.4,
  },
  {
    id: 5,
    title: "Bluetooth Speaker Mini",
    category: "Audio",
    price: 1599,
    rating: 4.1,
  },
  {
    id: 6,
    title: "USB-C Hub 7-in-1",
    category: "Accessories",
    price: 2199,
    rating: 4.3,
  },
  {
    id: 7,
    title: "4K Action Camera",
    category: "Cameras",
    price: 7999,
    rating: 4.5,
  },
  {
    id: 8,
    title: "Noise-cancelling Earbuds",
    category: "Audio",
    price: 3499,
    rating: 4.8,
  },
  {
    id: 9,
    title: "Fitness Band Lite",
    category: "Wearables",
    price: 1799,
    rating: 4.0,
  },
  {
    id: 10,
    title: "DSLR Prime Lens 50mm",
    category: "Cameras",
    price: 9999,
    rating: 4.7,
  },
  {
    id: 10,
    title: "Home Theatres",
    category: "Electronics",
    price: 12000,
    rating: 4.9,
  },
  {
    id: 10,
    title: "Men's Handwatch",
    category: "Fashion",
    price: 2000,
    rating: 4.5,
  },
];
